### ISSUE TITLE
Syntax Style

### ISSUE THREAD

**Issue by MNic** [dihi/development_guide#1]
# Python Syntax Style Unification
Syntax style is probably the most, or second most divisive python thing we do.  I've blatantly copied directly from Google and added a few (comments) of my own.  I'd be interested in your thoughts / preferences so that we can finalize these for the Style.md guide.

- module_name (from sqlalchemy import *create_engine*)
- package_name (import *sqlalchemy*)
- ClassName
- method_name (vs methodName)
- ExceptionName (*ValueError*)
- function_name (vs functionName)
- GLOBAL_CONSTANT_NAME
- global_var_name
- instance_var_name
- function_parameter_name
- local_var_name

**Comment by MNic** [comment]
I don't feel very strongly about the (comments), but there's a part of me that likes the fact that only variables, parameters really use the underscore.  It's also a little cathartic that methods and functions are similarly formatted since they're similar in...function.  

Having said that though.  I really don't feel strongly about it.  If '_' is easier to read/remember/teach I'm down for that.

**Comment by michaelgao8** [comment]
So could this be summarized as PascalCase for Classes and exceptions and underscores for everything else? I think that makes sense to me

**Comment by MNic** [comment]
PascalCase for classes, camelCase for methods and functions, underscores for everything else; I think.

**Comment by MNic** [comment]
```python

def getTireCost( number_of_tires: int, cost_per_tire: float ):
    """Calculates cost to replace all tires"""
    return number_of_tires * cost_per_tire

class AutoMobile(object):

    def __init__(self, number_of_wheels: int, number_of_doors: int, top_speed: float):
        """Creates an instance of AutoMobile with wheels, doors and a static top speed

        number_of_wheels (int): number of wheels on the vehicle
        number_of_doors (int): number of doors, typically 2 or 4
        top_speed (float): maximum speed in miles per hour
        """
        self.number_of_wheels = number_of_wheels
        self.number_of_doors = number_of_doors
        self.top_speed = top_speed

    def maxPossibleDistance(self, travel_time: float):
        """Calculates the maximum possible travel distance for the AutoMobile at top speed
            
        travel_time (float): length of time travelled in hours
        """
        return self.top_speed*travel_time
```  

```python
>>> sedan = AutoMobile(4,4, 180)
>>> sedan.maxPossibleDistance(2)
360
>>> dir(sedan)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', 
'__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', 
'__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', 
'__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 
'maxPossibleDistance', 'number_of_doors', 'number_of_wheels', 'top_speed']
```
Reasonable?

**Comment by michaelgao8** [comment]
eh, I kind of like keeping function names using snake_case; it allows for things like private methods to look more like other methods:

```python
def get_tire_cost( number_of_tires: int, cost_per_tire: float ):
    """Calculates cost to replace all tires"""
    return number_of_tires * cost_per_tire

class AutoMobile(object):

    def __init__(self, number_of_wheels: int, number_of_doors: int, top_speed: float):
        """Creates an instance of AutoMobile with wheels, doors and a static top speed

        number_of_wheels (int): number of wheels on the vehicle
        number_of_doors (int): number of doors, typically 2 or 4
        top_speed (float): maximum speed in miles per hour
        """
        self.number_of_wheels = number_of_wheels
        self.number_of_doors = number_of_doors
        self.top_speed = top_speed

    def max_possible_distance(self, travel_time: float):
        """Calculates the maximum possible travel distance for the AutoMobile at top speed
            
        travel_time (float): length of time traveled in hours
        """
        _verify_travel_time(travel_time)
        return self.top_speed*travel_time

    def _verify_travel_time(travel_time: float):
        """Verifies that travel_time is less than a year
        travel_time (float): length of time traveled in hours
        """
        if travel_time > 365 * 24:
            raise Exception('travel_time is not feasible')
        pass
```

**Comment by MNic** [comment]
Works for me, we'll follow Google's then.  I think that matches their format exactly.

We should probably add some language around function names starting with verbs / actions (`get_`).  Is my `max_` allowed up there?  Implied get if first word is an aggregation?

**Comment by suyashkumar** [comment]
Y'all may want to consider a linter to enforce style conventions (at least [PEP8](https://pypi.org/project/pep8/))! or better yet, consider something like [google/yapf](https://github.com/google/yapf) which is sort of like `gofmt` in that it will auto format your code (preferably on save). Not sure if`yapf` isn as good as `gofmt` so maybe it's not time to use it widely yet, but thought I'd chime in!

**Comment by suyashkumar** [comment]
also as per PEP8, function names [should be snake_case](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names). (just pointing that out should you guys choose to follow PEP8--ultimately you should decide whatever is best for you)!

**Comment by suyashkumar** [comment]
Demo of yapf: https://yapf.now.sh/

**Comment by MNic** [comment]
Closing since we reached consensus.  Thanks for the input @suyashkumar
