### ISSUE TITLE
Pandas Missing Docs

### ISSUE THREAD

**Issue by MNic** [dihi/development_guide#3]
# Pandas Documentation

We need to write the content for the Style guide for Pandas.  This should include things like 

- preferring `.loc[]`
- DataFrame(s) and object-of-objects basics
- preferring package functions over object methods where redundancy exists (`pd.merge` vs `df.merge`)
- pandas Timestamps, timezone conversion and NaT handling.
- index, multi-index, axis manipulations
- almost never `inplace=True`

It would probably be best to keep this one as Pandas focused as possible and pass other *Data Science Coding Best Practices* to the generic 'Style' guide or another, yet to be determined *Analytics* type guide.

**Comment by michaelgao8** [comment]
What does object-of-objects basics refer to?

**Comment by MNic** [comment]
DataFrames are a good example.

DataFrames are objects with their own dataframe-y methods.  DataFrames are made of Series objects that also have their own Series-y methods.  When you call a single column from a DataFrame it returns a series in *most* cases, but multiple columns will return a DataFrame.  Column types can be 'object'.  

It could just be a section on objects that's really a reinforcement of 'know what your data types are and what methods are available to you'.

I could see a situation where someone runs into issues with things like:

```python
>>> a = {'a':[1,2,3], 'b': [4,5,6]}
>>> z = pd.DataFrame(a)
>>> z
   a  b
0  1  4
1  2  5
2  3  6
>>> type(z.loc[:,['a']])
<class 'pandas.core.frame.DataFrame'>
>>> type(z.loc[:, 'a'])
<class 'pandas.core.series.Series'>
>>> type(z.a)
<class 'pandas.core.series.Series'>
```

This may be an edge case with the `.loc` specific focus we've got everywhere else.  Just thought I'd bring it up, just in case.

Also... DataFrames and Series have SO many methods!

**Comment by michaelgao8** [comment]
Early Pandas style has been committed. Will continue to be [WIP]
